// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYrvBblGU47Wu6olUSC8MgqsD4qIu_I4',
    appId: '1:67352335222:web:f48127a0786ff5a0106057',
    messagingSenderId: '67352335222',
    projectId: 'nftapp-e4093',
    authDomain: 'nftapp-e4093.firebaseapp.com',
    storageBucket: 'nftapp-e4093.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Ib0WXVBOplrVAvJ8bmv6oH8tx60EVm0',
    appId: '1:67352335222:android:2d5f86f8c2bb4211106057',
    messagingSenderId: '67352335222',
    projectId: 'nftapp-e4093',
    storageBucket: 'nftapp-e4093.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbTkYhCIbKDMN97WSpiiT2vzff_jsVcIw',
    appId: '1:67352335222:ios:13aa21f5974245f8106057',
    messagingSenderId: '67352335222',
    projectId: 'nftapp-e4093',
    storageBucket: 'nftapp-e4093.appspot.com',
    iosClientId: '67352335222-ofem2592iqpj6m49fude8ldvta4g57rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbTkYhCIbKDMN97WSpiiT2vzff_jsVcIw',
    appId: '1:67352335222:ios:13aa21f5974245f8106057',
    messagingSenderId: '67352335222',
    projectId: 'nftapp-e4093',
    storageBucket: 'nftapp-e4093.appspot.com',
    iosClientId: '67352335222-ofem2592iqpj6m49fude8ldvta4g57rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nftApp',
  );
}
